(() => {
  const $ = id => document.getElementById(id);
  const canvas = $('game'), ctx = canvas.getContext('2d'), menu = $('menu'), controls = $('controls'), toast = $('toast');
  const hpEls = [$('p1hp'), $('p2hp')], chEls = [$('p1ch'), $('p2ch')], timerEl = $('timer');
  const keys = new Set(), input = { x: 0, y: 0, attack: 0, ranged: 0, dash: 0, skill: 0, ultimate: 0, summon: 0 };
  let W = 1280, H = 720, DPR = 1, running = false, paused = false, last = 0, shake = 0, slow = 1, finish = '', camFlash = 0;
  const world = { time: 99, particles: [], projectiles: [], slashes: [], clones: [], rings: [], birds: [] };
  const floor = () => H * 0.78, clamp = (v, a, b) => Math.max(a, Math.min(b, v)), rnd = (a, b) => a + Math.random() * (b - a);

  function resize() { DPR = Math.min(devicePixelRatio || 1, 2); W = innerWidth; H = innerHeight; canvas.width = W * DPR; canvas.height = H * DPR; ctx.setTransform(DPR, 0, 0, DPR, 0, 0); }
  addEventListener('resize', resize); resize();

  class Fighter {
    constructor(id, x, spec, ai = false) { Object.assign(this, { id, x, y: floor(), vx: 0, vy: 0, w: 54, h: 116, face: id ? -1 : 1, hp: 100, chakra: 55, ai, combo: 0, stun: 0, inv: 0, aura: 0, guard: 0, name: spec.name, spec, cd: {} }); }
    read(enemy) {
      if (!this.ai) return { ...input, attack: keys.has('KeyJ') || input.attack, ranged: keys.has('KeyK') || input.ranged, dash: keys.has('KeyL') || input.dash, skill: keys.has('KeyU') || input.skill, summon: keys.has('KeyO') || input.summon, ultimate: keys.has('KeyI') || input.ultimate, x: (keys.has('ArrowRight') || keys.has('KeyD') ? 1 : 0) - (keys.has('ArrowLeft') || keys.has('KeyA') ? 1 : 0) || input.x, y: (keys.has('ArrowUp') || keys.has('KeyW') ? -1 : keys.has('ArrowDown') || keys.has('KeyS') ? 1 : 0) || input.y };
      const d = enemy.x - this.x, near = Math.abs(d) < 90, mid = Math.abs(d) < 300, act = { x: Math.sign(d), y: 0 };
      if (near) { act.x = Math.random() < .4 ? -Math.sign(d) : 0; act.attack = Math.random() < .06; }
      if (!mid && Math.random() < .025) act.dash = true;
      if (Math.abs(d) > 145 && Math.random() < .02) act.ranged = true;
      if (this.chakra > 35 && mid && Math.random() < .018) act.skill = true;
      if (this.chakra > 50 && enemy.hp < 70 && Math.random() < .009) act.summon = true;
      if (this.chakra > 82 && enemy.hp < 58 && Math.random() < .012) act.ultimate = true;
      if (this.y >= floor() && Math.random() < .007) this.vy = -830;
      return act;
    }
    update(dt, enemy) {
      for (const k in this.cd) this.cd[k] = Math.max(0, this.cd[k] - dt); this.stun = Math.max(0, this.stun - dt); this.inv = Math.max(0, this.inv - dt); this.aura = Math.max(0, this.aura - dt);
      this.chakra = clamp(this.chakra + dt * (this.guard ? 16 : 8), 0, 100); const a = this.read(enemy); this.face = enemy.x > this.x ? 1 : -1; this.guard = a.y > .55 && this.y >= floor() - 3;
      if (!this.stun) { this.vx += a.x * 2500 * dt; if (a.y < -.45 && this.y >= floor() - 2) this.vy = -900; if (a.dash && !this.cd.dash && this.chakra >= 9) this.substitution(); if (a.attack && !this.cd.attack) this.melee(enemy); if (a.ranged && !this.cd.ranged && this.chakra >= 7) this.ranged(); if (a.skill && !this.cd.skill && this.chakra >= 30) this.skill(enemy); if (a.summon && !this.cd.summon && this.chakra >= 48) this.summon(enemy); if (a.ultimate && !this.cd.ultimate && this.chakra >= 80) this.ultimate(enemy); }
      this.vy += 1820 * dt; this.vx *= Math.pow(.0015, dt); this.x = clamp(this.x + this.vx * dt, 55, W - 55); this.y += this.vy * dt; if (this.y > floor()) { this.y = floor(); this.vy = 0; }
    }
    substitution() { this.cd.dash = .78; this.chakra -= 9; this.inv = .34; this.vx = this.face * 1040; logClone(this.x, this.y, this.spec); burst(this.x, this.y - 50, '#e2e8f0', 22); world.rings.push({ x: this.x, y: this.y - 62, r: 12, life: .34, color: '#93c5fd' }); }
    melee(e) { this.cd.attack = .19; this.combo = (this.combo + 1) % 4; const pow = this.combo === 3 ? 13 : 7 + this.combo * 2; slash(this.x + this.face * 58, this.y - 72, this.face, this.spec.main, .22 + this.combo * .04); if (touch(this, e, 96, 98)) hurt(e, pow, this.face * (380 + this.combo * 90), this.combo === 3 ? -500 : -230, this); }
    ranged() { this.cd.ranged = .45; this.chakra -= 7; for (let i = -1; i <= 1; i++) world.projectiles.push({ owner: this, x: this.x + this.face * 50, y: this.y - 72 + i * 10, vx: this.face * (780 + Math.abs(i) * 80), vy: i * 40, r: 11, life: 1.2, dmg: 5, color: '#e5e7eb', spin: 0, kind: 'star' }); }
    skill(e) { this.cd.skill = 2.4; this.chakra -= 30; this.aura = .85; toastMsg(`${this.name}\nRAIJIN COMBO`); for (let i = 0; i < 5; i++) setTimeout(() => running && blinkHit(this, e, i), i * 95); }
    summon(e) { this.cd.summon = 5.4; this.chakra -= 48; toastMsg(`${this.name}\nINVOCACIÓN FÉNIX`); world.birds.push({ owner: this, x: this.x - this.face * 140, y: this.y - 210, vx: this.face * 560, life: 1.35, dmg: 17, color: this.spec.main }); world.rings.push({ x: this.x, y: this.y - 70, r: 20, life: .8, color: '#bbf7d0' }); }
    ultimate(e) { this.cd.ultimate = 8.5; this.chakra -= 80; this.aura = 1.7; shake = 42; slow = .45; camFlash = .4; toastMsg(`${this.name}\nDRAGÓN CELESTIAL`, 1600); for (let i = 0; i < 95; i++) world.particles.push({ x: this.x, y: this.y - 74, vx: rnd(-760, 760), vy: rnd(-760, 160), life: rnd(.45, 1.25), color: i % 3 ? this.spec.main : '#fde047', s: rnd(2, 8) }); setTimeout(() => { slow = 1; if (touch(this, e, 560, 240)) hurt(e, 34, this.face * 820, -620, this); shockwave(e.x, e.y - 82, this.spec.main); }, 520); }
  }

  const specs = [{ name: 'RYU KAZE', main: '#f97316', hair: '#fde047', dark: '#172554', eye: '#38bdf8' }, { name: 'KAI TSUKI', main: '#7c3aed', hair: '#e0e7ff', dark: '#111827', eye: '#fb7185' }];
  const p1 = new Fighter(0, 260, specs[0]), p2 = new Fighter(1, 980, specs[1], true);
  function touch(a, b, rw, rh) { return Math.abs(a.x - b.x) < rw && Math.abs((a.y - 66) - (b.y - 66)) < rh && b.inv <= 0; }
  function hurt(t, amount, kx, ky, by) { const blocked = t.guard && Math.sign(kx) !== t.face; const dmg = blocked ? amount * .35 : amount; t.hp = clamp(t.hp - dmg, 0, 100); t.chakra = clamp(t.chakra + (blocked ? 12 : 5), 0, 100); t.vx += blocked ? kx * .25 : kx; t.vy += blocked ? -80 : ky; t.stun = blocked ? .06 : .2; shake = Math.max(shake, blocked ? 6 : 14); burst(t.x, t.y - 70, blocked ? '#60a5fa' : '#ef4444', blocked ? 10 : 20); if (t.hp <= 0 && !finish) end(`${by.name} WINS`); }
  function blinkHit(a, e, i) { a.x = clamp(e.x - a.face * rnd(60, 115), 55, W - 55); slash(e.x + rnd(-32, 32), e.y - rnd(38, 112), a.face, '#67e8f9', .2); if (touch(a, e, 260, 150)) hurt(e, i === 4 ? 10 : 5, a.face * 260, i === 4 ? -420 : -120, a); }
  function logClone(x, y, spec) { world.clones.push({ x, y, spec, life: .45 }); }
  function slash(x, y, dir, color, life = .2) { world.slashes.push({ x, y, dir, color, life, max: life }); burst(x, y, color, 7); }
  function burst(x, y, color, n) { for (let i = 0; i < n; i++) world.particles.push({ x, y, vx: rnd(-310, 310), vy: rnd(-410, 110), life: rnd(.25, .75), color, s: rnd(2, 8) }); }
  function shockwave(x, y, color) { camFlash = .5; shake = 50; for (let i = 0; i < 5; i++) world.rings.push({ x, y, r: 20 + i * 20, life: .55 + i * .06, color }); }
  function toastMsg(t, ms = 1200) { toast.textContent = t; clearTimeout(toast._t); if (ms < 9000) toast._t = setTimeout(() => toast.textContent = '', ms); }
  function end(t) { finish = t; slow = 1; toastMsg(`${t}\nToca la pantalla para reiniciar`, 99999); }

  function drawBg(t) { const g = ctx.createLinearGradient(0, 0, 0, H); g.addColorStop(0, '#08111f'); g.addColorStop(.45, '#1e1b4b'); g.addColorStop(1, '#111827'); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); ctx.fillStyle = '#fde68a'; ctx.beginPath(); ctx.arc(W * .76, H * .17, 48, 0, 7); ctx.fill(); for (let i = 0; i < 90; i++) { ctx.fillStyle = `rgba(255,255,255,${.08 + (i % 5) * .025})`; ctx.fillRect((i * 137 + t * 9) % W, (i * 71) % (H * .45), 2, 2); } for (let l = 0; l < 5; l++) { ctx.fillStyle = `rgba(${28 + l * 19},${52 + l * 22},${85 + l * 18},${.44 + l * .1})`; ctx.beginPath(); ctx.moveTo(0, floor() - 95 - l * 34); for (let x = 0; x <= W + 90; x += 80) ctx.lineTo(x, floor() - 95 - l * 34 - Math.sin(x * .01 + t + l) * (34 + l * 4)); ctx.lineTo(W, H); ctx.lineTo(0, H); ctx.fill(); } ctx.fillStyle = '#1f2937'; ctx.fillRect(0, floor(), W, H - floor()); ctx.fillStyle = '#0f172a'; for (let x = 0; x < W; x += 62) { ctx.fillRect(x, floor() - 70, 18, 70); ctx.fillRect(x - 16, floor() - 82, 50, 14); } ctx.fillStyle = '#16a34a'; for (let x = 0; x < W; x += 24) ctx.fillRect(x, floor() + Math.sin(x + t) * 3, 18, 5); }
  function drawF(f) { ctx.save(); ctx.translate(f.x, f.y); ctx.scale(f.face, 1); if (f.aura || f.inv) { ctx.globalAlpha = f.inv ? .5 : .34; ctx.strokeStyle = f.inv ? '#e0f2fe' : f.spec.main; ctx.lineWidth = 8; ctx.beginPath(); ctx.ellipse(0, -64, 48 + Math.sin(performance.now() / 55) * 8, 88, 0, 0, 7); ctx.stroke(); ctx.globalAlpha = 1; } ctx.fillStyle = 'rgba(0,0,0,.36)'; ctx.beginPath(); ctx.ellipse(0, 6, 48, 12, 0, 0, 7); ctx.fill(); ctx.lineCap = 'round'; ctx.strokeStyle = '#e5e7eb'; ctx.lineWidth = 7; ctx.beginPath(); ctx.moveTo(18, -66); ctx.lineTo(48, -38); ctx.moveTo(-18, -66); ctx.lineTo(-44, -38); ctx.moveTo(14, -18); ctx.lineTo(30, 0); ctx.moveTo(-14, -18); ctx.lineTo(-30, 0); ctx.stroke(); fillRound(-23, -90, 46, 75, 12, f.spec.dark); fillRound(-31, -78, 62, 46, 13, f.spec.main); fillRound(-18, -130, 36, 39, 15, '#f3c7a6'); ctx.fillStyle = f.spec.hair; ctx.beginPath(); ctx.moveTo(-27, -120); ctx.lineTo(-9, -158); ctx.lineTo(5, -132); ctx.lineTo(23, -150); ctx.lineTo(22, -112); ctx.closePath(); ctx.fill(); ctx.fillStyle = f.spec.eye; ctx.fillRect(6, -113, 8, 3); ctx.restore(); }
  function fillRound(x, y, w, h, r, c) { ctx.fillStyle = c; ctx.beginPath(); ctx.roundRect(x, y, w, h, r); ctx.fill(); }
  function drawFX() { for (const c of world.clones) { ctx.globalAlpha = c.life / .45 * .45; drawGhost(c); } ctx.globalAlpha = 1; for (const pr of world.projectiles) { ctx.save(); ctx.translate(pr.x, pr.y); ctx.rotate(pr.spin); ctx.fillStyle = pr.color; for (let i = 0; i < 4; i++) { ctx.rotate(Math.PI / 2); ctx.fillRect(0, -3, 25, 6); } ctx.restore(); } for (const b of world.birds) { ctx.save(); ctx.translate(b.x, b.y); ctx.scale(b.owner.face, 1); ctx.fillStyle = b.color; ctx.beginPath(); ctx.moveTo(36, 0); ctx.quadraticCurveTo(-10, -46, -58, -7); ctx.quadraticCurveTo(-10, 38, 36, 0); ctx.fill(); ctx.restore(); } for (const s of world.slashes) { ctx.save(); ctx.globalAlpha = s.life / s.max; ctx.translate(s.x, s.y); ctx.scale(s.dir, 1); ctx.strokeStyle = s.color; ctx.lineWidth = 12; ctx.beginPath(); ctx.arc(0, 0, 54, -.95, .9); ctx.stroke(); ctx.restore(); } for (const r of world.rings) { ctx.globalAlpha = r.life; ctx.strokeStyle = r.color; ctx.lineWidth = 5; ctx.beginPath(); ctx.arc(r.x, r.y, r.r, 0, 7); ctx.stroke(); } for (const p of world.particles) { ctx.globalAlpha = clamp(p.life, 0, 1); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, p.s, p.s); } ctx.globalAlpha = 1; }
  function drawGhost(c) { ctx.save(); ctx.translate(c.x, c.y); fillRound(-25, -90, 50, 76, 12, c.spec.main); fillRound(-17, -128, 34, 38, 15, '#fff'); ctx.restore(); }

  function update(dt) { if (paused || finish) return; dt *= slow; world.time -= dt; if (world.time <= 0) end(p1.hp >= p2.hp ? 'RYU KAZE WINS' : 'KAI TSUKI WINS'); p1.update(dt, p2); p2.update(dt, p1); for (const p of world.projectiles) { p.x += p.vx * dt; p.y += p.vy * dt; p.spin += dt * 22; p.life -= dt; const e = p.owner === p1 ? p2 : p1; if (Math.hypot(p.x - e.x, p.y - (e.y - 70)) < 44 && e.inv <= 0) { hurt(e, p.dmg, Math.sign(p.vx) * 300, -130, p.owner); p.life = 0; } } for (const b of world.birds) { b.x += b.vx * dt; b.life -= dt; const e = b.owner === p1 ? p2 : p1; if (Math.abs(b.x - e.x) < 72 && Math.abs(b.y - (e.y - 80)) < 96) { hurt(e, b.dmg, b.owner.face * 580, -360, b.owner); b.life = 0; shockwave(e.x, e.y - 70, b.color); } } for (const arr of [world.particles, world.slashes, world.clones, world.rings]) for (const o of arr) { o.x += (o.vx || 0) * dt; o.y += (o.vy || 0) * dt; if (o.vy !== undefined) o.vy += 920 * dt; if (o.r) o.r += 260 * dt; o.life -= dt; } world.projectiles = world.projectiles.filter(o => o.life > 0 && o.x > -100 && o.x < W + 100); world.birds = world.birds.filter(o => o.life > 0 && o.x > -160 && o.x < W + 160); world.particles = world.particles.filter(o => o.life > 0); world.slashes = world.slashes.filter(o => o.life > 0); world.clones = world.clones.filter(o => o.life > 0); world.rings = world.rings.filter(o => o.life > 0); shake *= Math.pow(.018, dt); camFlash = Math.max(0, camFlash - dt); hpEls[0].style.width = p1.hp + '%'; hpEls[1].style.width = p2.hp + '%'; chEls[0].style.width = p1.chakra + '%'; chEls[1].style.width = p2.chakra + '%'; timerEl.textContent = Math.max(0, Math.ceil(world.time)); }
  function render(t) { ctx.save(); if (shake > 1) ctx.translate(rnd(-shake, shake), rnd(-shake, shake)); drawBg(t / 1000); drawFX(); drawF(p1); drawF(p2); if (camFlash > 0) { ctx.globalAlpha = camFlash; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, W, H); } ctx.restore(); }
  function loop(t) { const dt = Math.min(.033, (t - last) / 1000 || 0); last = t; if (running) { update(dt); render(t); } requestAnimationFrame(loop); } requestAnimationFrame(loop);
  function start() { running = true; finish = ''; Object.assign(p1, new Fighter(0, W * .22, specs[0])); Object.assign(p2, new Fighter(1, W * .78, specs[1], true)); Object.assign(world, { time: 99, particles: [], projectiles: [], slashes: [], clones: [], rings: [], birds: [] }); menu.style.display = 'none'; controls.classList.add('playing'); document.documentElement.requestFullscreen?.().catch(() => {}); toastMsg('ROUND 1\nFIGHT!'); }
  $('playBtn').onclick = start; $('howBtn').onclick = () => $('how').hidden = !$('how').hidden; addEventListener('keydown', e => { keys.add(e.code); if (e.code === 'KeyP') paused = !paused; }); addEventListener('keyup', e => keys.delete(e.code)); canvas.addEventListener('pointerdown', () => { if (finish) start(); });
  const stick = $('stick'), knob = stick.querySelector('i'); let sid = null; stick.addEventListener('pointerdown', e => { sid = e.pointerId; stick.setPointerCapture(sid); moveStick(e); }); stick.addEventListener('pointermove', e => { if (e.pointerId === sid) moveStick(e); }); stick.addEventListener('pointerup', () => { sid = null; input.x = input.y = 0; knob.style.transform = ''; }); function moveStick(e) { const r = stick.getBoundingClientRect(), cx = r.left + r.width / 2, cy = r.top + r.height / 2, dx = clamp(e.clientX - cx, -50, 50), dy = clamp(e.clientY - cy, -50, 50); input.x = Math.abs(dx) < 12 ? 0 : dx / 50; input.y = Math.abs(dy) < 12 ? 0 : dy / 50; knob.style.transform = `translate(${dx}px,${dy}px)`; }
  document.querySelectorAll('.buttons button').forEach(b => { const a = b.dataset.act; b.addEventListener('pointerdown', e => { e.preventDefault(); input[a] = 1; b.setPointerCapture(e.pointerId); }); b.addEventListener('pointerup', () => input[a] = 0); b.addEventListener('pointercancel', () => input[a] = 0); });
})();
