namespace FlowUI
{
    public static class FlowTheme
    {
        public static void ApplyModernTheme(UI app)
        {
            app.GlobalStyle
                .Rule("*", "box-sizing", "border-box")
                .Rule("body", "margin", "0")
                .Rule("body", "background", "#0b1020")
                .Rule("body", "color", "#e7ecff")
                .Rule("body", "font-family", "Inter, Segoe UI, Arial, sans-serif")
                .Rule(".flow-scaffold", "min-height", "100vh")
                .Rule(".flow-appbar", "padding", "16px 20px")
                .Rule(".flow-appbar", "background", "#141c33")
                .Rule(".flow-appbar", "border-bottom", "1px solid #263455")
                .Rule(".flow-appbar-title", "margin", "0")
                .Rule(".flow-body-slot", "padding", "20px")
                .Rule(".flow-bottom-slot", "padding", "12px 20px")
                .Rule(".flow-row", "display", "flex")
                .Rule(".flow-row", "gap", "12px")
                .Rule(".flow-column", "display", "flex")
                .Rule(".flow-column", "flex-direction", "column")
                .Rule(".flow-column", "gap", "12px")
                .Rule(".flow-wrap", "display", "flex")
                .Rule(".flow-wrap", "flex-wrap", "wrap")
                .Rule(".flow-wrap", "gap", "8px")
                .Rule(".flow-grid", "display", "grid")
                .Rule(".flow-grid", "gap", "12px")
                .Rule(".flow-card", "background", "#141c33")
                .Rule(".flow-card", "border", "1px solid #2a395f")
                .Rule(".flow-card", "border-radius", "16px")
                .Rule(".flow-card", "padding", "16px")
                .Rule(".flow-input", "width", "100%")
                .Rule(".flow-input", "padding", "10px 12px")
                .Rule(".flow-input", "border-radius", "10px")
                .Rule(".flow-input", "border", "1px solid #31456f")
                .Rule(".flow-textarea", "min-height", "120px")
                .Rule(".flow-textarea", "width", "100%")
                .Rule(".flow-textarea", "padding", "12px")
                .Rule(".flow-select", "width", "100%")
                .Rule(".flow-select", "padding", "10px")
                .Rule(".flow-slider", "width", "100%")
                .Rule(".flow-progress", "height", "10px")
                .Rule(".flow-progress", "border-radius", "999px")
                .Rule(".flow-progress", "background", "#233252")
                .Rule(".flow-progress-value", "height", "100%")
                .Rule(".flow-progress-value", "background", "linear-gradient(90deg,#4ea1ff,#59f6d1)")
                .Rule(".flow-progress-value", "border-radius", "999px")
                .Rule(".flow-chip", "display", "inline-block")
                .Rule(".flow-chip", "padding", "6px 10px")
                .Rule(".flow-chip", "border-radius", "999px")
                .Rule(".flow-chip", "background", "#24355b")
                .Rule(".flow-badge", "display", "inline-block")
                .Rule(".flow-badge", "padding", "4px 8px")
                .Rule(".flow-badge", "border-radius", "8px")
                .Rule(".flow-badge", "background", "#3d87ff")
                .Rule(".flow-avatar", "width", "40px")
                .Rule(".flow-avatar", "height", "40px")
                .Rule(".flow-avatar", "border-radius", "50%")
                .Rule(".flow-list-tile", "padding", "10px")
                .Rule(".flow-list-tile", "border", "1px solid #24355b")
                .Rule(".flow-list-tile", "border-radius", "12px")
                .Rule(".flow-list-title", "font-weight", "600")
                .Rule(".flow-list-subtitle", "opacity", "0.8")
                .Rule(".flow-fab-slot", "position", "fixed")
                .Rule(".flow-fab-slot", "right", "24px")
                .Rule(".flow-fab-slot", "bottom", "24px")
                .Rule(".flow-fab", "border", "0")
                .Rule(".flow-fab", "border-radius", "999px")
                .Rule(".flow-fab", "padding", "14px 18px")
                .Rule(".flow-fab", "background", "#3d87ff")
                .Rule(".flow-fab", "color", "#fff")
                .Rule("button", "cursor", "pointer");

            app.Responsive
                .AddMaxWidthRule(900, ".flow-row", "flex-direction", "column")
                .AddMaxWidthRule(900, ".flow-grid", "grid-template-columns", "1fr");
        }
    }
}
