const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rnd=(a,b)=>a+Math.random()*(b-a);
export class Fighter{constructor(team,x,asset,name,ai=false){Object.assign(this,{type:'hero',team,x,y:0,vx:0,vy:0,w:78,h:118,asset,name,ai,face:team? -1:1,hp:220,maxHp:220,chakra:70,stun:0,inv:0,cd:{},combo:0,target:null});}
think(g){if(!this.ai)return g.input.pressed();const enemies=g.entities.filter(e=>e.team!==this.team&&e.hp>0),t=enemies.sort((a,b)=>Math.abs(a.x-this.x)-Math.abs(b.x-this.x))[0];this.target=t;const d=t?t.x-this.x:0,a={x:Math.sign(d),y:0};if(Math.abs(d)<95){a.x=0;a.attack=Math.random()<.055;}if(Math.abs(d)>180&&Math.random()<.025)a.ranged=1;if(Math.abs(d)<290&&this.chakra>35&&Math.random()<.018)a.skill=1;if(this.chakra>50&&Math.random()<.01)a.summon=1;if(this.chakra>82&&t?.type==='hero'&&Math.random()<.01)a.ultimate=1;if(Math.abs(d)>330&&Math.random()<.025)a.dash=1;return a;}
update(dt,g){this.y=this.y||g.floor;for(const k in this.cd)this.cd[k]=Math.max(0,this.cd[k]-dt);this.stun=Math.max(0,this.stun-dt);this.inv=Math.max(0,this.inv-dt);this.chakra=clamp(this.chakra+dt*9,0,100);const a=this.think(g), target=this.target||g.enemyHero(this.team);if(target)this.face=target.x>this.x?1:-1;if(!this.stun){this.vx+=a.x*2300*dt;if(a.y<-.4&&this.y>=g.floor-2)this.vy=-880;if(a.dash&&this.chakra>=9&&!this.cd.dash){this.cd.dash=.75;this.inv=.3;this.chakra-=9;this.vx=this.face*1050;g.clone(this);}if(a.attack&&!this.cd.attack)this.attack(g);if(a.ranged&&!this.cd.ranged&&this.chakra>=7)this.ranged(g);if(a.skill&&!this.cd.skill&&this.chakra>=30)this.skill(g);if(a.summon&&!this.cd.summon&&this.chakra>=45)this.summon(g);if(a.ultimate&&!this.cd.ultimate&&this.chakra>=80)this.ultimate(g);}this.vy+=1800*dt;this.vx*=Math.pow(.0015,dt);this.x=clamp(this.x+this.vx*dt,35,g.mapW-35);this.y+=this.vy*dt;if(this.y>g.floor){this.y=g.floor;this.vy=0;}}
attack(g){this.cd.attack=.2;this.combo=(this.combo+1)%4;g.slash(this.x+this.face*60,this.y-76,this.face,this.team);for(const e of g.enemies(this))if(Math.abs(e.x-this.x)<95&&Math.abs(e.y-this.y)<130)g.hurt(e,18+this.combo*4,this.face*430,this.combo===3?-520:-240,this);}
ranged(g){this.cd.ranged=.45;this.chakra-=7;for(let i=-1;i<=1;i++)g.projectiles.push({team:this.team,x:this.x+this.face*55,y:this.y-76+i*10,vx:this.face*(820+Math.abs(i)*80),vy:i*35,dmg:11,life:1.2,kind:'star'});}
skill(g){this.cd.skill=2.2;this.chakra-=30;g.toast(`${this.name}\nCOMBO RELÁMPAGO`);for(let i=0;i<5;i++)setTimeout(()=>g.blinkHit(this,i),i*90);}
summon(g){this.cd.summon=4.8;this.chakra-=45;g.toast(`${this.name}\nINVOCACIÓN BESTIA`);g.summons.push({team:this.team,x:this.x-this.face*120,y:this.y-210,vx:this.face*620,life:1.25,dmg:30});}
ultimate(g){this.cd.ultimate=8;this.chakra-=80;g.toast(`${this.name}\nTÉCNICA FINAL`,1600);g.shake=45;g.flash=.45;for(let i=0;i<90;i++)g.particle(this.x,this.y-80,this.team);setTimeout(()=>{const e=g.enemyHero(this.team);if(e)g.hurt(e,64,this.face*900,-650,this);g.shock(e?.x||this.x,e?.y-80||this.y-80,this.team);},500);}}
export class Bot{constructor(team,x,asset){Object.assign(this,{type:'bot',team,x,y:0,vx:0,vy:0,w:48,h:68,asset,face:team?-1:1,hp:70,maxHp:70,atk:0});}update(dt,g){this.y=this.y||g.floor;const enemies=g.entities.filter(e=>e.team!==this.team&&e.hp>0),t=enemies.sort((a,b)=>Math.abs(a.x-this.x)-Math.abs(b.x-this.x))[0];if(t){this.face=t.x>this.x?1:-1;const d=t.x-this.x;if(Math.abs(d)>62)this.vx+=Math.sign(d)*900*dt;else if((this.atk-=dt)<=0){this.atk=.85;g.hurt(t,9,this.face*170,-80,this);g.slash(this.x+this.face*36,this.y-45,this.face,this.team);}}this.vx*=Math.pow(.01,dt);this.x=clamp(this.x+this.vx*dt,35,g.mapW-35);this.y=g.floor;}}
export class Tower{constructor(team,x,asset){Object.assign(this,{type:'tower',team,x,y:0,w:110,h:165,asset,hp:360,maxHp:360,cd:0});}update(dt,g){this.y=g.floor;this.cd-=dt;const t=g.entities.filter(e=>e.team!==this.team&&e.hp>0&&Math.abs(e.x-this.x)<430).sort((a,b)=>Math.abs(a.x-this.x)-Math.abs(b.x-this.x))[0];if(t&&this.cd<=0){this.cd=1.35;g.projectiles.push({team:this.team,x:this.x,y:this.y-145,vx:Math.sign(t.x-this.x)*520,vy:-60,dmg:24,life:1.1,kind:'fire'});}}}
export const helpers={clamp,rnd};
