import {createInput} from './input.js';
import {Fighter,Bot,Tower,clamp,rnd} from './entities.js';
import {createSpriteSheets,frame} from './sprites.js';
const canvas=document.getElementById('game'),c=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,DPR=1,last=0,mode='intro',intro=0,menuPulse=0;
const input=createInput(canvas), sprites=createSpriteSheets();
const g={sprites,mapW:2600,floor:520,cam:0,time:180,entities:[],projectiles:[],summons:[],fx:[],shake:0,flash:0,slow:1,input,enemies:o=>g.entities.filter(e=>e.team!==o.team&&e.hp>0).sort((a,b)=>Math.abs(a.x-o.x)-Math.abs(b.x-o.x)),enemyHero:t=>g.entities.find(e=>e.type==='hero'&&e.team!==t&&e.hp>0),toastText:'',toastTime:0,toast(t,ms=1300){g.toastText=t;g.toastTime=ms/1000;},burst(x,y,team,n=1){for(let i=0;i<n;i++)g.fx.push({kind:'p',x,y,vx:rnd(-460,460),vy:rnd(-560,150),life:rnd(.25,.95),s:rnd(2,8),color:team?'#a78bfa':'#f97316'});},slash(x,y,dir,team){g.fx.push({kind:'slash',x,y,dir,life:.22,max:.22,color:team?'#c4b5fd':'#fed7aa'});g.burst(x,y,team,9);},clone(o){g.fx.push({kind:'clone',x:o.x,y:o.y,team:o.team,face:o.face,life:.42,max:.42});},shock(x,y,team){g.flash=.45;g.shake=52;for(let i=0;i<5;i++)g.fx.push({kind:'ring',x,y,r:18+i*24,life:.62+i*.06,color:team?'#c4b5fd':'#facc15'});},hurt(e,d,kx,ky,by){if(e.inv)return;e.hp=clamp(e.hp-d,0,e.maxHp);e.vx=(e.vx||0)+kx;e.vy=(e.vy||0)+ky;e.stun=.18;g.shake=Math.max(g.shake,13);g.burst(e.x,e.y-e.h*.55,by.team,16);if(e.hp<=0){g.fx.push({kind:'text',text:e.type==='tower'?'TORRE DESTRUIDA':'KO',x:e.x,y:e.y-e.h,life:1.2});if(e.type==='hero'){mode='end';g.toast(`${by.name||'EQUIPO'} WINS\nTOCA PARA REINICIAR`,999999);}}},blink(a,i){const e=g.enemyHero(a.team);if(!e||a.hp<=0)return;a.x=clamp(e.x-a.face*rnd(70,125),40,g.mapW-40);g.slash(e.x+rnd(-32,32),e.y-rnd(45,115),a.face,a.team);g.hurt(e,i===4?24:12,a.face*280,i===4?-430:-130,a);}};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;c.setTransform(DPR,0,0,DPR,0,0);g.floor=H*.78;input.setLayout(W,H);}addEventListener('resize',resize);resize();
function start(){g.time=180;g.cam=0;g.projectiles=[];g.summons=[];g.fx=[];g.wave=0;g.shake=0;g.flash=0;g.slow=1;g.entities=[new Fighter(0,260,'RYU KAZE'),new Fighter(1,g.mapW-260,'KAI TSUKI',true),new Tower(0,115),new Tower(1,g.mapW-115)];spawnWave();mode='play';g.toast('OBISOFTDEV\nFIGHT!');document.documentElement.requestFullscreen?.().catch(()=>{});}
function spawnWave(){g.entities.push(new Bot(0,150),new Bot(0,200),new Bot(0,250),new Bot(1,g.mapW-150),new Bot(1,g.mapW-200),new Bot(1,g.mapW-250));}
function update(dt){if(mode==='intro'){intro+=dt;if(intro>3.7)mode='menu';return;}if(mode==='menu'||mode==='end'){menuPulse+=dt;if(input.state.start)start();return;}dt*=g.slow;g.time-=dt;if(g.time<=0){mode='end';g.toast('TIEMPO TERMINADO\nTOCA PARA REINICIAR',999999);}if((g.wave-=dt)<=0){g.wave=13;spawnWave();}for(const e of g.entities)e.update(dt,g);for(const p of g.projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=280*dt;p.spin+=dt*18;p.life-=dt;const t=g.entities.find(e=>e.team!==p.team&&e.hp>0&&Math.abs(e.x-p.x)<e.w*.75&&Math.abs((e.y-e.h*.55)-p.y)<e.h*.7);if(t){g.hurt(t,p.dmg,Math.sign(p.vx)*240,-130,{team:p.team,name:p.kind==='fire'?'TORRE':'SHINOBI'});p.life=0;}}for(const s of g.summons){s.x+=s.vx*dt;s.life-=dt;const t=g.entities.find(e=>e.team!==s.team&&e.hp>0&&Math.abs(e.x-s.x)<85);if(t){g.hurt(t,s.dmg,Math.sign(s.vx)*600,-330,{team:s.team,name:'BESTIA'});g.shock(t.x,t.y-82,s.team);s.life=0;}}for(const f of g.fx){f.x+=(f.vx||0)*dt;f.y+=(f.vy||0)*dt;if(f.vy!==undefined)f.vy+=920*dt;if(f.r)f.r+=280*dt;f.life-=dt;}g.entities=g.entities.filter(e=>e.hp>0||e.type==='hero');g.projectiles=g.projectiles.filter(p=>p.life>0&&p.x>-120&&p.x<g.mapW+120);g.summons=g.summons.filter(s=>s.life>0);g.fx=g.fx.filter(f=>f.life>0);const hero=g.entities.find(e=>e.type==='hero'&&e.team===0);g.cam=clamp((hero?.x||0)-W*.35,0,Math.max(0,g.mapW-W));g.shake*=Math.pow(.02,dt);g.flash=Math.max(0,g.flash-dt);g.toastTime=Math.max(0,g.toastTime-dt);}
function draw(){c.save();if(g.shake>1)c.translate(rnd(-g.shake,g.shake),rnd(-g.shake,g.shake));drawStage(performance.now()/1000);if(mode==='intro')drawIntro();else{drawWorld();drawHud();drawCanvasControls();if(mode==='menu')drawMenu();if(mode==='end')drawEnd();}if(g.toastTime>0)drawToast();if(g.flash){c.globalAlpha=g.flash;c.fillStyle='#fff';c.fillRect(0,0,W,H);c.globalAlpha=1;}c.restore();}
function drawStage(t){c.drawImage(sprites.tiles.img,0,0,sprites.tiles.w,sprites.tiles.h,0,0,W,H*.48);const sky=c.createLinearGradient(0,H*.3,0,H);sky.addColorStop(0,'#1e1b4b');sky.addColorStop(1,'#111827');c.fillStyle=sky;c.fillRect(0,H*.3,W,H*.7);c.save();c.translate(-g.cam*.18,0);c.fillStyle='#fde68a';c.beginPath();c.arc(1700,H*.14,58,0,7);c.fill();for(let i=0;i<110;i++){c.fillStyle=`rgba(255,255,255,${.08+(i%5)*.025})`;c.fillRect((i*151+t*10)%g.mapW-g.cam*.05,(i*73)%(H*.45),2,2);}for(let l=0;l<5;l++){c.fillStyle=`rgba(${25+l*22},${50+l*21},${88+l*18},${.42+l*.1})`;c.beginPath();c.moveTo(0,g.floor-100-l*34);for(let x=0;x<g.mapW+120;x+=85)c.lineTo(x,g.floor-100-l*34-Math.sin(x*.012+t+l)*38);c.lineTo(g.mapW,H);c.lineTo(0,H);c.fill();}c.restore();c.save();c.translate(-g.cam,0);c.fillStyle='#1f2937';c.fillRect(0,g.floor,g.mapW,H-g.floor);c.fillStyle='#0f172a';for(let x=0;x<g.mapW;x+=70){c.fillRect(x,g.floor-72,18,72);c.fillRect(x-16,g.floor-86,52,14);}c.fillStyle='#14532d';for(let x=0;x<g.mapW;x+=22)c.fillRect(x,g.floor+Math.sin(x+t)*4,18,5);c.restore();}
function drawWorld(){for(const p of g.projectiles){c.save();c.translate(p.x-g.cam,p.y);c.rotate(p.spin);c.fillStyle=p.kind==='fire'?'#f97316':'#e5e7eb';for(let i=0;i<4;i++){c.rotate(Math.PI/2);c.fillRect(0,-4,28,8);}c.restore();}for(const s of g.summons){c.save();c.translate(s.x-g.cam,s.y);c.fillStyle=s.team?'#a78bfa':'#f97316';c.beginPath();c.moveTo(58,0);c.quadraticCurveTo(-20,-58,-86,-8);c.quadraticCurveTo(-20,52,58,0);c.fill();c.restore();}for(const f of g.fx)drawFx(f);g.entities.sort((a,b)=>a.y-b.y).forEach(e=>{e.draw(c,g);drawLife(e);});}
function drawFx(f){c.save();c.globalAlpha=clamp(f.life/(f.max||1),0,1);if(f.kind==='p'){c.fillStyle=f.color;c.fillRect(f.x-g.cam,f.y,f.s,f.s);}if(f.kind==='slash'){c.translate(f.x-g.cam,f.y);c.scale(f.dir,1);c.strokeStyle=f.color;c.lineWidth=12;c.beginPath();c.arc(0,0,58,-.9,.9);c.stroke();}if(f.kind==='ring'){frame(c,sprites.fx,Math.floor((1-f.life)*8),f.x-g.cam,f.y,120+f.r,120+f.r,false);c.strokeStyle=f.color;c.lineWidth=5;c.beginPath();c.arc(f.x-g.cam,f.y,f.r,0,7);c.stroke();}if(f.kind==='clone'){const sh=f.team?sprites.hero1:sprites.hero0;frame(c,sh,0,f.x-g.cam,f.y,105,150,f.face<0);}if(f.kind==='text'){c.font='900 34px system-ui';c.fillStyle='#fff';c.fillText(f.text,f.x-g.cam-55,f.y);}c.restore();}
function drawLife(e){if(e.type==='hero'&&e.hp===e.maxHp)return;c.fillStyle='#020617cc';c.fillRect(e.x-g.cam-38,e.y-e.h-26,76,8);c.fillStyle=e.team?'#a78bfa':'#fb923c';c.fillRect(e.x-g.cam-38,e.y-e.h-26,76*e.hp/e.maxHp,8);}
function drawHud(){const a=g.entities.find(e=>e.type==='hero'&&e.team===0),b=g.entities.find(e=>e.type==='hero'&&e.team===1);bar(18,18,W*.36,18,a,'RYU KAZE',0);bar(W-W*.36-18,18,W*.36,18,b,'KAI TSUKI',1);c.fillStyle='#020617bb';round(W/2-38,12,76,46,16);c.fillStyle='#fff';c.font='900 28px system-ui';c.textAlign='center';c.fillText(Math.max(0,Math.ceil(g.time)),W/2,44);c.textAlign='left';}
function bar(x,y,w,h,p,name,team){c.fillStyle='#020617bb';round(x,y,w,45,14);c.fillStyle='#fff';c.font='900 13px system-ui';c.fillText(name,x+10,y+15);c.fillStyle='#111827';round(x+8,y+20,w-16,h,9);c.fillStyle=team?'#a78bfa':'#fb923c';round(x+8,y+20,(w-16)*(p?p.hp/p.maxHp:0),h,9);c.fillStyle='#0e7490';round(x+8,y+40,(w-16)*(p?p.chakra/100:0),6,5);}
function drawCanvasControls(){if(matchMedia('(hover:none)').matches||W<1100){const L=input.layout;c.globalAlpha=.82;c.strokeStyle='#ffffff55';c.lineWidth=2;c.beginPath();c.arc(L.stick.x,L.stick.y,L.stick.r,0,7);c.stroke();c.fillStyle='#38bdf8aa';c.beginPath();c.arc(L.stick.x+input.state.x*36,L.stick.y+input.state.y*36,28,0,7);c.fill();for(const [k,b] of Object.entries(L.buttons)){if(k==='start')continue;c.fillStyle=k==='ultimate'?'#ef4444cc':k==='skill'?'#7c3aedcc':k==='summon'?'#16a34acc':'#f97316cc';c.beginPath();c.arc(b.x,b.y,b.r,0,7);c.fill();c.fillStyle='#fff';c.font='900 12px system-ui';c.textAlign='center';c.fillText(k==='ranged'?'★':k.toUpperCase().slice(0,5),b.x,b.y+4);}c.textAlign='left';c.globalAlpha=1;}}
function drawIntro(){c.fillStyle='rgba(2,6,23,.35)';c.fillRect(0,0,W,H);c.save();c.translate(W/2,H/2);c.rotate(intro*1.8);c.strokeStyle='#facc15';c.lineWidth=6;c.beginPath();c.arc(0,0,Math.min(W,H)*.22,0,7);c.stroke();for(let i=0;i<6;i++){c.rotate(Math.PI/3);c.strokeRect(-50,-50,100,100);}c.restore();c.textAlign='center';c.fillStyle='#fde68a';c.font='900 18px system-ui';c.fillText('OBISOFTDEV PRESENTA',W/2,H*.34);c.fillStyle='#fff';c.font=`900 ${Math.min(72,W*.07)}px system-ui`;c.fillText('SHINOBI SENKI X',W/2,H*.48);c.font='700 16px system-ui';c.fillStyle='#bfdbfe';c.fillText('100% CANVAS · FULLSCREEN · BOTS · TORRES · SKILLS',W/2,H*.56);c.textAlign='left';}
function drawMenu(){panel('SHINOBI SENKI X','Batalla ninja estilo senki con gráficos dibujados en canvas, bots, torres, poderes y ultimate.', 'TOCA PARA JUGAR');}
function drawEnd(){panel('FIN DEL COMBATE',g.toastText.split('\n')[0]||'RESULTADO','TOCA PARA REINICIAR');}
function panel(title,body,button){c.fillStyle='rgba(2,6,23,.72)';c.fillRect(0,0,W,H);c.fillStyle='rgba(15,23,42,.92)';round(W/2-330,H/2-150,660,300,28);c.strokeStyle='#ffffff33';c.strokeRect(W/2-310,H/2-130,620,260);c.textAlign='center';c.fillStyle='#fff';c.font='900 48px system-ui';c.fillText(title,W/2,H/2-65);c.fillStyle='#dbeafe';c.font='600 17px system-ui';c.fillText(body,W/2,H/2-18);const b=input.layout.buttons.start;c.fillStyle='#f97316';round(b.x-b.w/2,b.y-b.h/2,b.w,b.h,20);c.fillStyle='#1c1917';c.font='900 20px system-ui';c.fillText(button,b.x,b.y+7);c.textAlign='left';}
function drawToast(){c.textAlign='center';c.fillStyle='#fff';c.font='900 34px system-ui';g.toastText.split('\n').forEach((line,i)=>c.fillText(line,W/2,H*.18+i*40));c.textAlign='left';}
function round(x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
