import {loadAssets} from './assets.js';
import {createInput,bindTouch} from './input.js';
import {Fighter,Bot,Tower,helpers} from './entities.js';
const {clamp,rnd}=helpers, $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d'),menu=$('menu'),controls=$('controls'),toastEl=$('toast'),timerEl=$('timer'),hp=[$('p1hp'),$('p2hp')],ch=[$('p1ch'),$('p2ch')];
let W=innerWidth,H=innerHeight,DPR=1,assets,input,running=false,last=0,camera=0;
const g={mapW:2400,floor:520,time:180,entities:[],projectiles:[],summons:[],fx:[],shake:0,flash:0,input:null,enemies:o=>g.entities.filter(e=>e.team!==o.team&&e.hp>0),enemyHero:t=>g.entities.find(e=>e.type==='hero'&&e.team!==t&&e.hp>0),toast:(t,ms=1200)=>{toastEl.textContent=t;clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.textContent='',ms);},particle:(x,y,team)=>g.fx.push({x,y,vx:rnd(-420,420),vy:rnd(-520,120),life:rnd(.3,.9),s:rnd(3,9),c:team?'#a78bfa':'#f97316'}),slash:(x,y,dir,team)=>{g.fx.push({slash:1,x,y,dir,life:.22,max:.22,c:team?'#c4b5fd':'#fed7aa'});for(let i=0;i<8;i++)g.particle(x,y,team);},clone:o=>g.fx.push({clone:o.asset,x:o.x,y:o.y,life:.42,max:.42,dir:o.face}),shock:(x,y,team)=>{g.flash=.45;g.shake=48;for(let i=0;i<5;i++)g.fx.push({ring:1,x,y,r:20+i*24,life:.6+i*.06,c:team?'#c4b5fd':'#facc15'});},hurt:(e,d,kx,ky,by)=>{if(e.inv)return;e.hp=clamp(e.hp-d,0,e.maxHp);e.vx=(e.vx||0)+kx;e.vy=(e.vy||0)+ky;e.stun=.18;g.shake=Math.max(g.shake,12);for(let i=0;i<14;i++)g.particle(e.x,e.y-e.h*.55,by.team);if(e.hp<=0){g.fx.push({text:e.type==='tower'?'TORRE DESTRUIDA':'KO',x:e.x,y:e.y-e.h,life:1.1});if(e.type==='hero'){running=false;g.toast(`${by.name||'EQUIPO'} WINS\nToca para reiniciar`,99999);}}},blinkHit:(a,i)=>{const e=g.enemyHero(a.team);if(!e||a.hp<=0)return;a.x=clamp(e.x-a.face*rnd(70,120),40,g.mapW-40);g.slash(e.x+rnd(-30,30),e.y-rnd(40,110),a.face,a.team);g.hurt(e,i===4?24:12,a.face*270,i===4?-420:-120,a);}};
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);g.floor=H*.78;}addEventListener('resize',resize);resize();
function spawnWave(){g.entities.push(new Bot(0,130,assets.minion),new Bot(0,170,assets.minion),new Bot(1,g.mapW-130,assets.minion),new Bot(1,g.mapW-170,assets.minion));}
function reset(){g.time=180;g.entities=[new Fighter(0,260,assets.ryu,'RYU KAZE'),new Fighter(1,g.mapW-260,assets.kai,'KAI TSUKI',true),new Tower(0,95,assets.tower),new Tower(1,g.mapW-95,assets.tower)];g.projectiles=[];g.summons=[];g.fx=[];g.wave=0;g.shake=0;g.flash=0;spawnWave();running=true;menu.style.display='none';controls.classList.add('playing');document.documentElement.requestFullscreen?.().catch(()=>{});g.toast('OBISOFTDEV\nBATALLA INICIADA');}
function update(dt){g.time-=dt;if(g.time<=0){running=false;g.toast('TIEMPO TERMINADO\nToca para reiniciar',99999);}if((g.wave-=dt)<=0){g.wave=14;spawnWave();}for(const e of g.entities)e.update(dt,g);for(const p of g.projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.life-=dt;const t=g.entities.find(e=>e.team!==p.team&&e.hp>0&&Math.abs(e.x-p.x)<e.w*.7&&Math.abs((e.y-e.h*.55)-p.y)<e.h*.65);if(t){g.hurt(t,p.dmg,Math.sign(p.vx)*230,-120,{team:p.team,name:'TORRE'});p.life=0;}}for(const s of g.summons){s.x+=s.vx*dt;s.life-=dt;const t=g.entities.find(e=>e.team!==s.team&&e.hp>0&&Math.abs(e.x-s.x)<80);if(t){g.hurt(t,s.dmg,Math.sign(s.vx)*560,-320,{team:s.team,name:'BESTIA'});g.shock(t.x,t.y-80,s.team);s.life=0;}}for(const f of g.fx){f.x+=(f.vx||0)*dt;f.y+=(f.vy||0)*dt;if(f.vy!==undefined)f.vy+=900*dt;if(f.r)f.r+=260*dt;f.life-=dt;}g.entities=g.entities.filter(e=>e.hp>0||e.type==='hero');g.projectiles=g.projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<g.mapW+100);g.summons=g.summons.filter(s=>s.life>0);g.fx=g.fx.filter(f=>f.life>0);const p=g.entities.find(e=>e.type==='hero'&&e.team===0);camera=clamp((p?.x||camera)-W*.35,0,g.mapW-W);g.shake*=Math.pow(.02,dt);g.flash=Math.max(0,g.flash-dt);const heroes=[g.entities.find(e=>e.type==='hero'&&e.team===0),g.entities.find(e=>e.type==='hero'&&e.team===1)];heroes.forEach((p,i)=>{if(p){hp[i].style.width=100*p.hp/p.maxHp+'%';ch[i].style.width=p.chakra+'%';}});timerEl.textContent=Math.ceil(g.time);}
function bg(t){const grd=ctx.createLinearGradient(0,0,0,H);grd.addColorStop(0,'#07111f');grd.addColorStop(.5,'#1e1b4b');grd.addColorStop(1,'#111827');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-camera*.25,0);ctx.fillStyle='#fde68a';ctx.beginPath();ctx.arc(1600,H*.16,55,0,7);ctx.fill();for(let l=0;l<5;l++){ctx.fillStyle=`rgba(${30+l*22},${54+l*18},${90+l*20},${.45+l*.09})`;ctx.beginPath();ctx.moveTo(0,g.floor-100-l*32);for(let x=0;x<g.mapW+200;x+=90)ctx.lineTo(x,g.floor-100-l*32-Math.sin(x*.012+t+l)*38);ctx.lineTo(g.mapW,H);ctx.lineTo(0,H);ctx.fill();}ctx.restore();ctx.save();ctx.translate(-camera,0);ctx.fillStyle='#1f2937';ctx.fillRect(0,g.floor,g.mapW,H-g.floor);ctx.fillStyle='#0f172a';for(let x=0;x<g.mapW;x+=70){ctx.fillRect(x,g.floor-72,18,72);ctx.fillRect(x-15,g.floor-86,50,14);}ctx.restore();}
function drawEntity(e){ctx.save();ctx.translate(e.x-camera,e.y);ctx.scale(e.face||1,1);const img=e.asset, w=e.w*(e.type==='tower'?1.5:1.7), h=e.h*(e.type==='tower'?1.55:1.55);ctx.drawImage(img,-w/2,-h,w,h);ctx.restore();if(e.type!=='hero'||e.hp<e.maxHp){ctx.fillStyle='#020617aa';ctx.fillRect(e.x-camera-34,e.y-e.h-24,68,7);ctx.fillStyle=e.team?'#a78bfa':'#fb923c';ctx.fillRect(e.x-camera-34,e.y-e.h-24,68*e.hp/e.maxHp,7);}}
function drawFX(){for(const p of g.projectiles){ctx.save();ctx.translate(p.x-camera,p.y);ctx.fillStyle=p.kind==='fire'?'#f97316':'#e5e7eb';ctx.rotate(performance.now()/55);for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillRect(0,-4,24,8);}ctx.restore();}for(const s of g.summons){ctx.save();ctx.translate(s.x-camera,s.y);ctx.fillStyle=s.team?'#a78bfa':'#f97316';ctx.beginPath();ctx.moveTo(54,0);ctx.quadraticCurveTo(-18,-54,-80,-8);ctx.quadraticCurveTo(-18,48,54,0);ctx.fill();ctx.restore();}for(const f of g.fx){ctx.globalAlpha=clamp(f.life/(f.max||1),0,1);if(f.clone)ctx.drawImage(f.clone,f.x-camera-50,f.y-150,100,150);else if(f.slash){ctx.strokeStyle=f.c;ctx.lineWidth=12;ctx.beginPath();ctx.arc(f.x-camera,f.y,58,-.9,.9);ctx.stroke();}else if(f.ring){ctx.strokeStyle=f.c;ctx.lineWidth=5;ctx.beginPath();ctx.arc(f.x-camera,f.y,f.r,0,7);ctx.stroke();}else if(f.text){ctx.font='900 34px system-ui';ctx.fillStyle='#fff';ctx.fillText(f.text,f.x-camera-45,f.y);}else{ctx.fillStyle=f.c;ctx.fillRect(f.x-camera,f.y,f.s,f.s);}}ctx.globalAlpha=1;}
function render(t){ctx.save();if(g.shake>1)ctx.translate(rnd(-g.shake,g.shake),rnd(-g.shake,g.shake));bg(t/1000);drawFX();g.entities.sort((a,b)=>a.y-b.y).forEach(drawEntity);if(g.flash){ctx.globalAlpha=g.flash;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);}ctx.restore();}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(running){update(dt);render(t);}requestAnimationFrame(loop);}requestAnimationFrame(loop);
loadAssets().then(a=>{assets=a;input=createInput();g.input=input;bindTouch(input);$('playBtn').onclick=reset;$('howBtn').onclick=()=>$('how').hidden=!$('how').hidden;canvas.addEventListener('pointerdown',()=>{if(!running)reset();});});
